### ISSUE TITLE
0002-use-gnu-printf.patch moves again...

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#11]
Lars,

Good day.  Re trunk, thought I'd give you a head's up that:

Configure.in -> Configure.ac -> tool/m4/ruby_check_printf_prefix.m4

My patch is at [tool-m4-ruby_check_printf_prefix.m4.patch](https://github.com/MSP-Greg/ruby-loco/tree/b341909564cbe7bdd906ea2a2cefedcaca3a87f1/patches/gte20600)

Thanks, Greg

**Comment by larskanis** [comment]
Merged per [this commit](https://github.com/oneclick/rubyinstaller2-packages/commit/f4d4f0b48080d64c51fa957408dbf625169e489d) - thank you!
