### ISSUE TITLE
OpenSSL - MSYS2/MinGW added (broken) 1.1.1 package

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#12]
@larskanis

1. MSYS2 moved to OpenSSL 1.1.1 and it's currently broken.  Main issue may be repo's that are using whatever Appveyor has, or worse, updating OpenSSL with a pacman upgrade.  As you know, only affects 2.4.

2. Unknown what Appveyor will do.  Haven't asked.

3. I decided that ruby-loco will only be for trunk, rebuilt it so it runs all with two PowerShell scripts (one is build/install, one is test).  Runs locally.

4. None of the tests utilize `make`, all are run from the install folder's Ruby.  Took a few patches for that.

I'll probably save a few of the MSYS2 OpenSSL packages to BinTray and use those for CI.

Hope things are well, Greg

**Comment by MSP-Greg** [comment]
It hasn't hit the package repository yet, but MSYS2 released OpenSSL 1.1.1-4, and it is building/testing fine with ruby-loco.

It's basically the same package as the one I built, with a few config changes, no old API removal, and it does have docs.

**Comment by MSP-Greg** [comment]
@larskanis

Thanks for your work on the new versions.  Re 2.5 & OpenSSL 1.1.1, please see https://github.com/ruby/ruby/commit/1dfc377 (rhenium is the main maintainer of ruby/openssl) and https://bugs.ruby-lang.org/issues/15219.

EDIT: Prior to edit, listed an issue that was caused by my doing an in-place update, which already had updates to RubyGems & Bundler installed.

**Comment by MSP-Greg** [comment]
JFYI, I just ran the net & openssl tests from ruby_2_5 test-all on the 2.5.3 build.

openssl was fine, net had a few issues.  After applying r64234 (the above patch), all net tests passed.

**Comment by larskanis** [comment]
The patch will be backported to ruby-2.5.4: https://bugs.ruby-lang.org/issues/15219
Thanks @MSP-Greg ! Closing now.
