### ISSUE TITLE
Might ruby-loco use dll_directory?

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#17]
Lars,

Good day.

Would you mind if I used [`dll_directory`](https://github.com/oneclick/rubyinstaller2-packages/blob/master/mingw-w64-ruby-head/0001-Add-C-ext-win32-dll_directory-as-an-alternative-to-f.patch) in ruby-loco's mingw & ucrt builds?

I am asking, so feel free to say no...

Thanks,  Greg

**Comment by larskanis** [comment]
Sure, use it for what ever you like! :smile: 
Maybe it's useful for ruby-core as well, but I didn't request it so far. So it is only available as this patch file.

**Comment by MSP-Greg** [comment]
Thank you.  And thanks for maintaining RI2.  Some people seem to think that it magically maintains itself, especially around Christmas.

> Maybe it's useful for ruby-core as well

Agree with that.  And portable bash binstubs.

I wonder how many Windows Ruby users do not use RI2 builds?  I suspect very few build their own.

Also, [microsoft/vcpkg](https://github.com/microsoft/vcpkg) has a lot of packages, so I wonder about mswin popularity.  There are gems that won't build with it.
