### ISSUE TITLE
MSYS2 updated to OpenSSL 3

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#19]
And, cert & conf files are in etc/ssl, not ssl…

Question - Will Ruby 3.1 continue with OpenSSL 1.1.1?

Asking because GitHub Actions code will need to be changed if Ruby 3.1 changes to OpenSSL 3.0.x...

**Comment by larskanis** [comment]
Thank you for the hint! I opened an issue at MSYS2 regarding the path change: https://github.com/msys2/MINGW-packages/issues/15141

**Comment by MSP-Greg** [comment]
We'll see what happens.  I don't feel strongly about it, as determining what version of OpenSSL is compiled against is trivial.  I've already changed ruby-loco to use etc/ssl.

Not that many repos build against OpenSSL, but until it's sorted out, your package and the current MSYS2 package aren't compatible.  Makes GitHub Actions setup a bit messy.

**Comment by MSP-Greg** [comment]
One possible benefit from etc/ssl is that the 3.0.x config file (`openssl.cnf`) is in a different location that the 1.1.1 file.

Or, Actions needs to work with older versions of Ruby, but MSYS2 mingw/ucrt apps may need to find certs, and they're all built with OpenSSL 3.  So, OpenSSL 1.1.1 will have a full install, but the OpenSSL 3 dll's and files in `etc/ssl` will be included (speaking of Actions setup of `C:/msys64`).

**Comment by larskanis** [comment]
For me this issue is solved so far. I just didn't want to follow an unintended change. We'll see if a mixture of OpenSSL-1.1 and 3.0 will work. For ruby-pg at least I didn't encounter any issues after switching it to OpenSSL-3.0 on older Rubies.

**Comment by MSP-Greg** [comment]
Thanks.  I should have the changes for GitHub Actions soon.  Below is a recent Puma run:
```
                         Puma::MiniSSL                   Ruby OpenSSL
OPENSSL_LIBRARY_VERSION: OpenSSL 3.0.7 1 Nov 2022        OpenSSL 1.1.1s  1 Nov 2022
        OPENSSL_VERSION: OpenSSL 3.0.7 1 Nov 2022        OpenSSL 1.1.1s  1 Nov 2022
```

Puma doesn't load Ruby's OpenSSL, and both can find the dll's they need, but other gems may have issues...

**Comment by MSP-Greg** [comment]
Lars,

May I copy the openssl-1.1.1.w-1 packages for use with setup-ruby?  As you may recall, there's logic to use 1.1.1 for older Rubies...

Hope things are well, Greg

**Comment by larskanis** [comment]
Sure, you can use the package. There will be no version 1.1.1x, but my plan is to use the Ubuntu patches, which are provided until 2025-04, to patch security issues of OpenSSL-1.1.1. This luckily fits to the EOL of Ruby-3.1 and it worked well for the current ruby-3.0 and 3.1 release.

**Comment by MSP-Greg** [comment]
Thanks.

> my plan is to use the Ubuntu patches

Very good idea.  Not that either of us want to encourage use of 1.1.1.  The same could be said about old Rubies...

**Comment by larskanis** [comment]
OpenSSL-1.x was OK for me and I was about to seriously hate OpenSSL-3.x for their breaking changes to low level crypto API! This is because we do a lot of low level crypto routines in our company through ruby-openssl and it took me several week to get them all to the OpenSSL-3.x API. It also required some ugly and complicated ways to implement it on the 3.x API. But now everything works and I'm fine with OpenSSL-3.x again.

**Comment by MSP-Greg** [comment]
> I was about to seriously hate OpenSSL-3.x for their breaking changes to low level crypto API!

I'm not sure when or how, but I've had the impression you were a crypto type.  I had a lot of 'space-time' math years ago, but never any related to crypto.  For me, it's kind of a black box, stuff goes in and out, but that's about it.  I was aware of the issues 3.x caused with ruby-openssl...
