### ISSUE TITLE
libffi in PKGBUILD ?

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#7]
I was checking rbconfig.rb to see if there were any 'system specific' artifacts that shouldn't exist.  The only ones I found were a few in the compile flags referencing `msys64/mingw64/lib/libffi-3.2.1/include`.

Checked the ruby travis and appveyor files, and no mention, then looked around the repo and found a commit of Nobu's referencing build issues on mswin.  Nobu is generally aware of mswin and MinGW issues, so he would normally pick up both if required.  It was done in 2.4 days, and backported to 2.3 and maybe 2.2.

Anyway, both of our PKGBUILD files have something similar in the build section:

```
local FFI_INC=$(pkg-config --cflags libffi)
CPPFLAGS+=" -DFD_SETSIZE=2048 ${FFI_INC}"
CFLAGS+=" ${FFI_INC}"
```

See [2.4 PKKBUILD](https://github.com/oneclick/rubyinstaller2-packages/blob/8609117d7eecc587860d8ff3a4a1e67ead6eeae9/mingw-w64-ruby24/PKGBUILD#L45-L47) and [2.5 PKGBUILD](https://github.com/oneclick/rubyinstaller2-packages/blob/8609117d7eecc587860d8ff3a4a1e67ead6eeae9/mingw-w64-ruby25/PKGBUILD#L47-L49).

I removed anything related to libffi, and built trunk and 2.3.4.  Both had the same amount of test-all failures/errors as previous builds.  There were actually increases in tests and assertions, and the two measures of skips dropped.  Both of the `rbconfig.rb` files were artifact free.  I also ran the fiddle tests in a windows cmd shell (no make), and they passed.

I haven't checked thouroughly, but I think this may be something that's out of date, and has never been checked for whether it's still required.   It's listed in the original [PKGBUILD](https://github.com/Alexpux/MINGW-packages/commit/5e1f72b3a27720aac5d8352b84d2ec2eebe30f52) from 2013-12-03.  `fiddle.so` still requires `libffi-6.dll`, but the flags may not be needed.

Hence, you might have a look, as I'm rather 'c' challenged...

Sorry about forgetting the dll in GDBM...

**Comment by larskanis** [comment]
I also wondered about the libffi reference in `rbconfig`, but didn't investigate it, so far. It looks like some leftover from previous versions. If you want to fix it, I'm open to receive your PR.

**Comment by MSP-Greg** [comment]
Thanks.  I wasn't sure if you had a reason for leaving it, and that I didn't remove it without checking into it...  I'll file a PR.
