### ISSUE TITLE
Json - may require ragel package for building

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2-packages#9]
Testing a bunch of builds, and I noticed the issue with 2.4.1.

Most tests I can run on 2.4.1 with something similar to
```
ruby -v runner.rb -I. --show-skip json
```

Json has a seg fault.

EDIT: I can do a PR and add it to the PKGBUILD depends section, wasn't sure if you had any other PR's/commits ready.   Have to be a bit later...

**Comment by larskanis** [comment]
As commented in #10 ragel is not a build dependency for MRI.
